language: python
python:
  - "3.5"
before_script:
  - pip install coverage
  - pip install coveralls
script:
  - coverage run test_rpn.py
after_success:
  - COVERALLS_REPO_TOKEN=6Wb1bgXol7Y9qOgsvGob3ngyVmQ2Fyabz coveralls
